#!/bin/bash

cd ~/
figlet -c slideshow # Generates title banner 
sleep 5 # Wait for USB drive to mount
sudo blkid -s UUID -o value > uuid_scan_results.txt 
UUID_FILE=$(cat uuid_scan_results.txt)

sudo lsusb > ~/lsusb.txt
numofusb=`cat lsusb.txt | wc -l`

uuidmenu() {
	echo "Select USB Drive's UUID"
	i=1
	for j in $UUID_FILE
	do
		echo " $i) $j"
		uuid[i]=$j
		let i++
	done

	read -p "Enter number: " input
	echo "You select the UUID: ${uuid[$input]}"
}

slideshow() {
	uuid_menu
	# mounts usb drive
	sudo mount --uuid ${uuid[$input]} ~/usb_drive
	# copies images into new folder
	sudo mv ~/usb_drive/usb/*.jpg ~/Desktop/pictures 
	echo "Images have been copied from usb drive to ~/Desktop/pictures"
	# Run eog command to start slideshow
	eog --slide-show ~/Desktop/pictures
    	# unmounts usb drive
	sudo umount ~/usb_drive
	echo "usb drive has been unmounted!"
}

if [ $numofusb -ge 2 ]
then
# check if ~/usb_drive exist 
  if [ -d ~/usb_drive ] 
  then
	  slideshow
  else
	  # else if usb drive does not exist
	  sudo mkdir ~/usb_drive && echo "~/usb_drive directory has been made!"
	  slideshow	
  fi
else
  if [ -d ~/usb_drive ]
  then
    eog --slide-show ~/Desktop/pictures
  else
    sudo mkdir ~/usb_drive && echo "~/usb_drive directory has been made!"
    eog --slide-show ~/Desktop/pictures
  fi
fi
