#!/bin/bash

cd ~/
figlet -c slideshow # Generates title banner 
echo "Select USB Drive's UUID"
sleep 5 # Wait for USB drive to mount
blkid -s UUID -o value > uuid_scan_results.txt 
UUID_FILE=$(cat uuid_scan_results.txt)

i=1
for j in $UUID_FILE
do
	echo " $i) $j"
	uuid[i]=$j
	i=$(( i + 1 ))
done
 
read -p "Enter number: " input
echo "You select the UUID: ${uuid[$input]}"

# check if ~/usb_drive exist 
if [ -d ~/usb_drive ] 
then
	# mounts usb drive
	sudo mount --uuid ${uuid[$input]} ~/usb_drive

	# copies images into new folder
	sudo mv ~/usb_drive/usb/*.jpg ~/Desktop/pictures 
	echo Images have been copied from usb drive to ~/Desktop/pictures

	# Run eog command to start slideshow
	eog --slide-show ~/Desktop/pictures
        
	sudo umount ~/usb_drive
	echo usb drive has been unmounted!
else
	# else if usb drive does not exist
	sudo mkdir ~/usb_drive
        echo ~/usb_drive directory has been made!

	sudo mount --uuid ${uuid[$input]} ~/usb_drive
	sudo mv ~/usb_drive/usb/*.jpg ~/Desktop/pictures

	eog --slide-show ~/Desktop/pictures
	
	sudo umount ~/usb_drive
	echo usb drive has been unmounted!
fi
